---
### Dotnet Requests Pod
apiVersion: v1
kind: Pod
metadata:
  name: client-dotnet-test
spec:
  containers:
  - name: client-dotnet-test
    image: docker.io/stevelsplunk/splk-dotnet5
    env:
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: SIGNALFX_ENDPOINT_URL
      value: "http://$(SPLUNK_OTEL_AGENT):9411/api/v2/spans"
    - name: SIGNALFX_SERVICE_NAME
      value: dotnet5-httpget
    - name: SIGNALFX_ENV
      value: <ENV PREFIX>-apm-workshop
    - name: CORECLR_ENABLE_PROFILING
      value: "1"
    - name: CORECLR_PROFILER
      value: '{B4C89B0F-9908-4F73-9F59-0D77C5A06874}'
    - name: CORECLR_PROFILER_PATH
      value: /opt/signalfx/SignalFx.Tracing.ClrProfiler.Native.so
    - name: SIGNALFX_TRACE_DEBUG
      value: "true"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]